# Generated by Django 3.0.8 on 2020-07-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=20)),
                ('office_number', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=2)),
                ('primary_manager_id', models.IntegerField()),
                ('function_id', models.IntegerField()),
            ],
        ),
    ]
