# Generated by Django 3.0.8 on 2020-07-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_auto_20200709_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='employment_status',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='employment_type',
            field=models.CharField(default='Employee', max_length=10),
            preserve_default=False,
        ),
    ]
