# Generated by Django 3.0.8 on 2020-07-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_auto_20200711_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='doj',
            field=models.DateField(default='2014-04-28'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='dos',
            field=models.DateField(default='9999-12-31'),
            preserve_default=False,
        ),
    ]
