# Generated by Django 3.0.8 on 2020-07-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_auto_20200711_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetail',
            old_name='doj',
            new_name='date_of_joining',
        ),
        migrations.RenameField(
            model_name='employeedetail',
            old_name='dos',
            new_name='date_of_separation',
        ),
    ]
