# Generated by Django 3.0.8 on 2020-07-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_auto_20200711_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='emp_id',
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
