# Generated by Django 3.0.8 on 2020-07-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_auto_20200711_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='primary_manager_id',
            field=models.IntegerField(),
        ),
    ]
