# Generated by Django 3.0.8 on 2020-07-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0007_auto_20200711_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetail',
            old_name='primary_manager_id',
            new_name='primary_manager',
        ),
    ]
