# Generated by Django 3.0.8 on 2020-07-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0009_auto_20200711_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('function_name', models.CharField(max_length=50)),
                ('function_manager', models.IntegerField()),
                ('function_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('project_url', models.CharField(max_length=255)),
                ('project_description', models.CharField(max_length=255)),
                ('project_manager', models.IntegerField()),
                ('project_owner', models.IntegerField(blank=True, null=True)),
                ('project_ba', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='EmployeeDetail',
            new_name='Employee',
        ),
    ]
