# Generated by Django 3.0.8 on 2020-07-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0010_auto_20200711_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
