# Generated by Django 3.0.8 on 2020-07-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0011_auto_20200711_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='noreply@webmd.net', max_length=254),
            preserve_default=False,
        ),
    ]
