# Generated by Django 3.0.8 on 2020-07-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0013_auto_20200712_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='function_id',
            new_name='primary_function',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='primary_manager_id',
            new_name='primary_manager',
        ),
    ]
