# Generated by Django 3.0.8 on 2020-07-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0016_auto_20200718_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSummary',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=50)),
                ('manager_name', models.CharField(max_length=200)),
                ('function_name', models.CharField(max_length=50)),
                ('function_manager', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'org_vw_employee_overview',
                'managed': False,
            },
        ),
    ]
