# Generated by Django 3.0.8 on 2020-07-25 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org', '0017_employeesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeIdName',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=152)),
            ],
            options={
                'db_table': 'org_vw_employee_id_name',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='function',
            name='function_manager',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='org.Employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_ba',
            field=models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ba_employee', to='org.Employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pm_employee', to='org.Employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_owner',
            field=models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='po_employee', to='org.Employee'),
        ),
    ]
