# Generated by Django 3.0.8 on 2020-07-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0018_auto_20200725_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionIdName',
            fields=[
                ('function_id', models.IntegerField(primary_key=True, serialize=False)),
                ('function_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'org_vw_employee_id_name',
                'managed': False,
            },
        ),
    ]
