# Generated by Django 3.0.8 on 2020-07-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0019_functionidname'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='functionidname',
            table='org_vw_function',
        ),
    ]
