# Generated by Django 3.0.8 on 2020-07-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0020_auto_20200725_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default='1900-01-01', help_text='Format: YYYY-MM-DD'),
            preserve_default=False,
        ),
    ]
