# Generated by Django 3.0.8 on 2020-07-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0022_auto_20200726_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, default='bhawesh003@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
