# Generated by Django 3.0.8 on 2020-08-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0024_auto_20200803_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionSummary',
            fields=[
                ('function_id', models.IntegerField(primary_key=True, serialize=False)),
                ('function_name', models.CharField(max_length=200)),
                ('function_manager', models.CharField(max_length=200)),
                ('function_description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'org_vw_function_summary',
                'managed': False,
            },
        ),
    ]
