# Generated by Django 3.0.8 on 2020-08-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0025_functionsummary'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='functionsummary',
            table='org_vw_function_overview',
        ),
    ]
