# Generated by Django 3.0.8 on 2020-08-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0026_auto_20200803_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSummary',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('project_owner', models.CharField(max_length=200)),
                ('project_manager', models.CharField(max_length=200)),
                ('business_analyst', models.CharField(max_length=200)),
                ('project_description', models.CharField(max_length=200)),
                ('project_url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'org_vw_project_overview',
                'managed': False,
            },
        ),
    ]
