# Generated by Django 3.0.8 on 2020-08-03 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0027_projectsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='primary_manager',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='org.Employee'),
            preserve_default=False,
        ),
    ]
