# Generated by Django 3.0.9 on 2020-08-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0029_auto_20200810_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSummary',
        ),
    ]
