# Generated by Django 3.0.9 on 2020-08-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0030_delete_employeesummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FunctionSummary',
        ),
        migrations.DeleteModel(
            name='ProjectSummary',
        ),
    ]
