# Generated by Django 3.0.9 on 2020-08-11 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0033_auto_20200811_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('role_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='AvailableUserID',
        ),
        migrations.RenameField(
            model_name='function',
            old_name='function_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='function',
            old_name='function_manager',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='function',
            old_name='function_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_ba',
            new_name='ba',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_manager',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='projectmapping',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Project'),
        ),
        migrations.AddField(
            model_name='projectmapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.ProjectRole'),
        ),
    ]
