# Generated by Django 3.0.9 on 2020-08-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0034_auto_20200811_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmapping',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
