# Generated by Django 3.0.9 on 2020-08-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0036_auto_20200818_1147'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectmapping',
            unique_together={('project', 'member')},
        ),
    ]
