# Generated by Django 3.0.9 on 2020-08-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0037_auto_20200818_1614'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectmapping',
            unique_together=set(),
        ),
    ]
