# Generated by Django 3.0.9 on 2020-08-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0038_auto_20200819_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ba',
        ),
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
