# Generated by Django 3.0.9 on 2020-08-26 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0040_auto_20200825_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='primary_function',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='org.Function'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='primary_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='org.Employee'),
        ),
        migrations.AlterField(
            model_name='function',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='org.Employee'),
        ),
        migrations.AlterField(
            model_name='projectmapping',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='org.Employee'),
        ),
        migrations.AlterField(
            model_name='projectmapping',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='org.Project'),
        ),
        migrations.AlterField(
            model_name='projectmapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='org.ProjectRole'),
        ),
    ]
