# Generated by Django 3.0.9 on 2020-08-26 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0041_auto_20200826_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmapping',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Employee'),
        ),
        migrations.AlterField(
            model_name='projectmapping',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Project'),
        ),
        migrations.AlterField(
            model_name='projectmapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.ProjectRole'),
        ),
    ]
