# Generated by Django 3.0.9 on 2020-08-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0042_auto_20200826_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_resignation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
