# Generated by Django 3.0.9 on 2020-08-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0043_employee_date_of_resignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmapping',
            name='bandwidth',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
