# Generated by Django 3.0.9 on 2020-08-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0044_projectmapping_bandwidth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectrole',
            old_name='role_description',
            new_name='description',
        ),
    ]
