# Generated by Django 3.0.9 on 2020-08-31 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org', '0045_auto_20200828_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_employee', models.BooleanField(default=False)),
                ('add_function', models.BooleanField(default=False)),
                ('add_project', models.BooleanField(default=False)),
                ('manager_actions', models.BooleanField(default=False)),
                ('team_salary_access', models.BooleanField(default=False)),
                ('all_salary_access', models.BooleanField(default=False)),
                ('all_access', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
