# Generated by Django 3.0.9 on 2020-09-02 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0047_auto_20200902_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolemapping',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Employee', unique=True),
        ),
    ]
