# Generated by Django 3.0.9 on 2020-09-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0048_auto_20200902_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='functional_manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_shift_start',
            field=models.TimeField(default='09:00:00', null=True),
        ),
    ]
