# Generated by Django 3.0.9 on 2020-09-06 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org', '0049_auto_20200904_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employee_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_date',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='employee',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employee_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='modified_date',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='function',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='function_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='function',
            name='created_date',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='function',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='function_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='function',
            name='modified_date',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='project_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='project',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='project_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='modified_date',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='projectmapping',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='project_mapping_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmapping',
            name='created_date',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='projectmapping',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='project_mapping_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmapping',
            name='modified_date',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='project_role_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='created_date',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='project_role_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='modified_date',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='userrolemapping',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_role_mapping_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrolemapping',
            name='created_date',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='userrolemapping',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_role_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrolemapping',
            name='modified_date',
            field=models.DateTimeField(default='1900-01-01'),
        ),
    ]
