# Generated by Django 3.0.9 on 2020-10-01 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0051_auto_20200930_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmapping',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='org.ProjectRole'),
        ),
    ]
