# Generated by Django 3.0.9 on 2020-10-10 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org', '0052_auto_20201001_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default='1900-01-01')),
                ('modified_date', models.DateTimeField(default='1900-01-01')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='skill_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='skill_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkillMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default='1900-01-01')),
                ('modified_date', models.DateTimeField(default='1900-01-01')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employee_skill_mapping_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='org.Employee')),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employee_skill_mapping_modified_by', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='org.Skill')),
            ],
        ),
    ]
