# Generated by Django 3.0.9 on 2020-10-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0054_auto_20201019_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
