# Generated by Django 3.0.9 on 2020-10-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0056_auto_20201019_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeskillmapping',
            name='proficiency',
            field=models.IntegerField(default=5),
        ),
    ]
