# Generated by Django 3.0.9 on 2020-10-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0057_employeeskillmapping_proficiency'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeeskillmapping',
            constraint=models.UniqueConstraint(fields=('employee', 'skill'), name='unique_employee_skill'),
        ),
    ]
