# Generated by Django 3.0.9 on 2020-10-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0058_auto_20201021_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmapping',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='org.Skill'),
        ),
    ]
