# Generated by Django 3.0.9 on 2020-10-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0059_auto_20201021_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='change_comment',
            field=models.CharField(default='Initial Record', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='change_effective_from',
            field=models.DateField(default='1900-01-01', help_text='Format: YYYY-MM-DD'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_resignation',
            field=models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_separation',
            field=models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True),
        ),
    ]
