# Generated by Django 3.0.9 on 2020-10-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0061_auto_20201026_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='personal_email_address',
            new_name='personal_email',
        ),
    ]
